-- 示例文章数据（user_id = 1）
-- 请在MySQL中执行以下SQL语句

INSERT INTO articles (title, content, user_id, created_at, updated_at) VALUES 
('Go语言入门指南：从零开始学习Golang', 'Go（又称Golang）是Google开发的一种静态强类型、编译型、并发型，并具有垃圾回收功能的编程语言。\n\n## 为什么选择Go？\n\n1. **简洁高效**：语法简洁，学习曲线平缓\n2. **高性能**：接近C语言的执行效率\n3. **并发支持**：原生支持goroutine和channel\n4. **跨平台**：轻松编译为多平台可执行文件\n5. **丰富的标准库**：网络、加密、JSON等开箱即用\n\n## 快速开始\n\n安装Go后，创建hello.go文件：\n\n```go\npackage main\n\nimport \"fmt\"\n\nfunc main() {\n    fmt.Println(\"Hello, Go!\")\n}\n```\n\n运行命令：`go run hello.go`\n\n## 总结\n\nGo语言非常适合构建高性能的网络服务、微服务和云原生应用。', 1, DATE_SUB(NOW(), INTERVAL 5 DAY), DATE_SUB(NOW(), INTERVAL 5 DAY)),

('Gin框架实战：构建RESTful API的最佳实践', 'Gin是一个用Go (Golang)编写的高性能HTTP Web框架。它具有类似Martini的API，但性能更好。\n\n## 核心特性\n\n- **快速**：基于Radix树的路由，内存占用小\n- **中间件支持**：HTTP请求可以经过一系列中间件处理\n- **崩溃恢复**：可以捕获panic，保证服务稳定\n- **JSON验证**：可以解析和验证请求的JSON\n- **路由分组**：更好地组织API\n\n## 基本使用示例\n\n```go\npackage main\n\nimport (\n    \"github.com/gin-gonic/gin\"\n)\n\nfunc main() {\n    r := gin.Default()\n    \n    r.GET(\"/ping\", func(c *gin.Context) {\n        c.JSON(200, gin.H{\n            \"message\": \"pong\",\n        })\n    })\n    \n    r.Run(\":8080\")\n}\n```\n\n## 最佳实践\n\n1. 合理组织项目结构\n2. 使用中间件处理通用逻辑\n3. 统一错误处理\n4. 添加适当的日志\n5. 编写单元测试', 1, DATE_SUB(NOW(), INTERVAL 3 DAY), DATE_SUB(NOW(), INTERVAL 3 DAY)),

('MySQL与Redis配合使用：打造高性能Web应用', '在现代Web应用中，MySQL和Redis的组合是非常常见的技术选型。\n\n## MySQL的作用\n\n- **持久化存储**：存储核心业务数据\n- **事务支持**：保证数据一致性\n- **复杂查询**：支持SQL进行数据分析\n- **关系维护**：外键约束确保数据完整性\n\n## Redis的应用场景\n\n1. **缓存层**：缓存热点数据，减轻数据库压力\n2. **Session存储**：分布式Session管理\n3. **排行榜**：利用有序集合实现实时排名\n4. **计数器**：文章阅读量、点赞数等\n5. **消息队列**：发布订阅模式实现异步处理\n\n## 架构设计建议\n\n```\n客户端 → Nginx → Gin应用 → Redis缓存 → MySQL数据库\n```\n\n### 缓存策略\n\n- **Cache Aside**：先查缓存，未命中再查DB\n- **Write Through**：写入时同步更新缓存\n- **Write Behind**：异步批量写入\n- **设置合理的过期时间**\n\n## 性能优化技巧\n\n1. 使用连接池管理数据库连接\n2. Redis Pipeline减少网络往返\n3. 合理设计索引\n4. 监控慢查询日志\n5. 定期分析和优化SQL', 1, DATE_SUB(NOW(), INTERVAL 7 DAY), DATE_SUB(NOW(), INTERVAL 7 DAY)),

('Docker容器化部署：让Go应用一键上线', 'Docker可以帮助我们快速部署Go应用，保证环境一致性。\n\n## Dockerfile示例\n\n```dockerfile\n# 构建阶段\nFROM golang:1.21-alpine AS builder\nWORKDIR /app\nCOPY go.mod go.sum ./\nRUN go mod download\nCOPY . .\nRUN CGO_ENABLED=0 GOOS=linux go build -o main .\n\n# 运行阶段\nFROM alpine:latest\nRUN apk --no-cache add ca-certificates\nWORKDIR /root/\nCOPY --from=builder /app/main .\nEXPOSE 8080\nCMD [\"./main\"]\n```\n\n## docker-compose.yml\n\n```yaml\nversion: \'3.8\'\nservices:\n  app:\n    build: .\n    ports:\n      - \"8080:8080\"\n    depends_on:\n      - mysql\n      - redis\n  \n  mysql:\n    image: mysql:8.0\n    environment:\n      MYSQL_ROOT_PASSWORD: password\n  \n  redis:\n    image: redis:7-alpine\n```\n\n## 部署步骤\n\n1. 编写Dockerfile和docker-compose.yml\n2. 构建镜像：`docker-compose build`\n3. 启动服务：`docker-compose up -d`\n4. 查看日志：`docker-compose logs -f`\n\n## 生产环境建议\n\n- 设置资源限制（CPU、内存）\n- 配置健康检查\n- 使用Volume持久化数据\n- 配置日志收集\n- 设置自动重启策略', 1, DATE_SUB(NOW(), INTERVAL 10 DAY), DATE_SUB(NOW(), INTERVAL 10 DAY)),

('Go并发编程深入理解：Goroutine与Channel', 'Go语言的并发模型是其最强大的特性之一。\n\n## Goroutine\n\nGoroutine是轻量级线程，创建成本极低：\n\n```go\ngo func() {\n    fmt.Println(\"Hello from goroutine\")\n}()\n```\n\n## Channel\n\nChannel用于在goroutine之间通信：\n\n```go\nch := make(chan string)\n\ngo func() {\n    ch <- \"Hello\" // 发送数据\n}()\n\nmsg := <-ch // 接收数据\nfmt.Println(msg)\n```\n\n## 常见模式\n\n### Worker Pool\n```go\njobs := make(chan int, 100)\nresults := make(chan int, 100)\n\n// 启动worker\nfor w := 1; w <= 3; w++ {\n    go worker(w, jobs, results)\n}\n\n// 发送任务\nfor j := 1; j <= 9; j++ {\n    jobs <- j\n}\nclose(jobs)\n```\n\n### Select语句\n用于等待多个channel操作：\n\n```go\nselect {\ncase msg1 := <-ch1:\n    fmt.Println(msg1)\ncase msg2 := <-ch2:\n    fmt.Println(msg2)\ncase <-time.After(time.Second):\n    fmt.Println(\"timeout\")\n}\n```\n\n## 最佳实践\n\n1. 不要通过共享内存通信，而要通过通信共享内存\n2. 使用buffered channel控制并发度\n3. 使用context取消goroutine\n4. 避免goroutine泄漏\n5. 合理使用sync包中的原语', 1, NOW(), NOW());
